
import React, { useState, useEffect } from 'react';
import { Camera } from './components/Camera';
import { ResultDisplay } from './components/ResultDisplay';
import { LoginScreen } from './components/LoginScreen';
import { Feed } from './components/Feed';
import { ChatList } from './components/ChatList';
import { ChatScreen } from './components/ChatScreen';
import { SettingsScreen } from './components/SettingsScreen';
import { SetupScreen } from './components/SetupScreen';
import { SplashScreen, ProcessingScreen, ErrorScreen } from './components/LoadingStates';
import { Header, Navigation } from './components/AppLayout';
import { analyzeMood } from './services/geminiService';
import { StorageService } from './services/storageService';
import { AppState, MoodResult, Post, Tab, User, ChatThread, FeedScope } from './types';

export default function App() {
  // State
  const [appState, setAppState] = useState<AppState>(AppState.LOGIN);
  const [activeTab, setActiveTab] = useState<Tab>(Tab.FEED);
  const [capturedImage, setCapturedImage] = useState<string | null>(null);
  const [moodResult, setMoodResult] = useState<MoodResult | null>(null);
  const [isInitializing, setIsInitializing] = useState(true);
  const [setupRequired, setSetupRequired] = useState(false);
  
  // Real Data State
  const [currentUser, setCurrentUser] = useState<User | null>(null);
  const [feedPosts, setFeedPosts] = useState<Post[]>([]);
  const [myChats, setMyChats] = useState<ChatThread[]>([]);
  const [feedScope, setFeedScope] = useState<FeedScope>(FeedScope.FRIENDS);
  const [requestCount, setRequestCount] = useState(0);
  
  // Chat State
  const [activeChatUser, setActiveChatUser] = useState<User | null>(null);
  
  // Flow State
  const [cameraOrigin, setCameraOrigin] = useState<'FEED' | 'CHAT'>('FEED');

  // Initialize
  useEffect(() => {
    const init = async () => {
      try {
        // 1. Check System Health (Missing Tables?)
        const health = await StorageService.checkSystemHealth();
        if (!health.healthy && health.error === 'MISSING_TABLES') {
            setSetupRequired(true);
            setIsInitializing(false);
            return;
        }

        const existingUser = await StorageService.getCurrentUser();
        if (existingUser) {
          setCurrentUser(existingUser);
          setAppState(AppState.MAIN_APP);
          await refreshData();
        }
      } catch (e) {
        console.error("Init error", e);
      } finally {
        // Ensure the animation plays for at least a split second to look nice
        setTimeout(() => setIsInitializing(false), 800);
      }
    };
    init();
  }, []);

  useEffect(() => {
    if (currentUser) {
      refreshData();
    }
  }, [feedScope]);

  const refreshData = async () => {
    const posts = await StorageService.getFeed(feedScope);
    setFeedPosts(posts);
    
    const chats = await StorageService.getChats();
    setMyChats(chats);
    
    // Refresh user data too
    const user = await StorageService.getCurrentUser();
    if (user) {
        setCurrentUser(user);
        setRequestCount(user.incomingRequests?.length || 0);
    }
  };

  // --- ACTIONS ---

  const handleLoginSuccess = async (user: User) => {
    setCurrentUser(user);
    setAppState(AppState.MAIN_APP);
    await refreshData();
  };

  const handleLogout = async () => {
    await StorageService.logout();
    setCurrentUser(null);
    setAppState(AppState.LOGIN);
    setActiveTab(Tab.FEED);
    setActiveChatUser(null);
  };

  const startCamera = (origin: 'FEED' | 'CHAT' = 'FEED') => {
    setCameraOrigin(origin);
    setAppState(AppState.CAMERA);
  };

  const handleCapture = async (imageSrc: string) => {
    setCapturedImage(imageSrc);
    setAppState(AppState.PROCESSING);

    try {
      const result = await analyzeMood(imageSrc);
      setMoodResult(result);
      setAppState(AppState.RESULT);
    } catch (error) {
      console.error(error);
      setAppState(AppState.ERROR);
    }
  };

  const handleRetake = () => {
    setCapturedImage(null);
    setMoodResult(null);
    setAppState(AppState.CAMERA);
  };

  const handlePostToFeed = async (isPublicArg?: boolean) => {
    // Ensure isPublic is definitely a boolean or undefined, not an event object
    const isPublic = typeof isPublicArg === 'boolean' ? isPublicArg : undefined;

    if (capturedImage && moodResult && currentUser) {
      const newPost: Post = {
        id: '', // ID generated by DB
        userId: currentUser.id,
        userSnapshot: currentUser,
        imageSrc: capturedImage,
        mood: moodResult,
        timestamp: Date.now(),
        likes: [],
        comments: [],
        isPublic: isPublic
      };
      
      // 1. Create Post
      const createdPost = await StorageService.createPost(newPost);
      
      // 2. Logic based on Origin
      if (cameraOrigin === 'CHAT' && activeChatUser) {
          // If we are in chat mode, immediately send this post to the chat
          await StorageService.sendMessage(activeChatUser.id, "", createdPost.id);
          await refreshData();
          
          setCapturedImage(null);
          setMoodResult(null);
          setAppState(AppState.MAIN_APP);
          // Stay in Chat tab, active user remains
      } else {
          // Standard Feed Post
          await refreshData();
          
          setCapturedImage(null);
          setMoodResult(null);
          setAppState(AppState.MAIN_APP);
          setActiveTab(Tab.FEED);
      }
    }
  };
  
  const handleTabChange = (tab: Tab) => {
      setActiveTab(tab);
      if (tab !== Tab.CHAT) {
          setActiveChatUser(null);
      }
  };

  // --- RENDER ---

  if (setupRequired) {
    return <SetupScreen />;
  }

  if (isInitializing) {
    return <SplashScreen />;
  }

  // Theme Helpers
  const isLight = currentUser?.settings?.theme === 'light';
  const bgClass = isLight ? 'bg-slate-100 md:bg-slate-50' : 'bg-black md:bg-slate-950';
  const appContainerClass = isLight ? 'bg-white' : 'bg-slate-950';
  const textClass = isLight ? 'text-slate-900' : 'text-slate-100';

  return (
    <div className={`min-h-screen flex items-center justify-center md:p-4 font-sans transition-colors duration-500 ${bgClass} ${textClass}`}>
       <div className={`w-full h-[100dvh] md:h-[850px] md:max-w-[400px] md:rounded-3xl overflow-hidden md:shadow-2xl md:border md:border-slate-800/50 relative flex flex-col transition-colors duration-500 ${appContainerClass}`}>
          
          {/* 1. LOGIN SCREEN */}
          {appState === AppState.LOGIN && (
            <LoginScreen 
                onLoginSuccess={handleLoginSuccess} 
            />
          )}

          {/* 2. MAIN APP CONTENT */}
          {appState === AppState.MAIN_APP && currentUser && (
             <>
              {/* Header (Hidden if inside a Chat) */}
              {!activeChatUser && (
                <Header 
                    currentUser={currentUser} 
                    onSettingsClick={() => setActiveTab(Tab.SETTINGS)} 
                    isLight={isLight}
                />
              )}

              {/* Content Area */}
              <div className={`flex-1 h-full transition-colors duration-500 ${appContainerClass}`}>
                {activeTab === Tab.FEED && (
                  <Feed 
                    posts={feedPosts} 
                    currentUser={currentUser} 
                    onRefresh={refreshData} 
                    currentScope={feedScope}
                    onScopeChange={setFeedScope}
                  />
                )}
                {activeTab === Tab.CHAT && (
                   activeChatUser ? (
                      <ChatScreen 
                        friend={activeChatUser} 
                        currentUser={currentUser} 
                        onBack={() => setActiveChatUser(null)} 
                        onCameraClick={() => startCamera('CHAT')}
                      />
                   ) : (
                      <ChatList 
                        chats={myChats} 
                        currentUser={currentUser}
                        onAddFriend={refreshData} 
                        onOpenChat={(friend) => setActiveChatUser(friend)}
                      />
                   )
                )}
                {activeTab === Tab.SETTINGS && (
                  <SettingsScreen user={currentUser} onUpdateUser={setCurrentUser} onLogout={handleLogout} />
                )}
              </div>

              {/* Navigation (Hidden if inside a Chat) */}
              {!activeChatUser && (
                <Navigation 
                    activeTab={activeTab}
                    onTabChange={handleTabChange}
                    onCameraClick={() => startCamera('FEED')}
                    requestCount={requestCount}
                    isLight={isLight}
                />
              )}
             </>
          )}
          
          {/* 3. CAMERA FLOW OVERLAYS */}
          {appState === AppState.CAMERA && (
            <div className="absolute inset-0 z-50 bg-black animate-in fade-in duration-200">
              <Camera onCapture={handleCapture} onCancel={() => setAppState(AppState.MAIN_APP)} />
            </div>
          )}
          
          {appState === AppState.PROCESSING && (
            <div className="absolute inset-0 z-50 bg-black">
              <ProcessingScreen capturedImage={capturedImage} />
            </div>
          )}
          
          {appState === AppState.RESULT && capturedImage && moodResult && (
            <div className="absolute inset-0 z-50 bg-slate-900">
              <ResultDisplay 
                imageSrc={capturedImage} 
                result={moodResult} 
                onRetake={handleRetake} 
                onPost={handlePostToFeed}
              />
            </div>
          )}

          {appState === AppState.ERROR && (
            <div className="absolute inset-0 z-50">
               <ErrorScreen onRetake={handleRetake} />
            </div>
          )}

       </div>
    </div>
  );
}
